/**
 * @file This file is autogenerated as part of the "prebuild" procedure.
 *	Modifications will be overwritten on rebuild.
 * @description Necessary because the JavaScript bundler doesn't support dynamic
 *	imports. Otherwise the dynamic code could be:
 *	```js
 *	import fs from 'node:fs/promises';
 *	fs.readdir('./').then(files => files
 *	 .filter(f => /^[^._].*.schema.json$/.test(f))
 *	 .map(f => f.replace(/.schema.json$/i,''))
 *	 .map(f => ({
 *		schema: './'+f+'.schema.json',
 *		transformer: './'+f+'.transformer.js'
 *	  }) )
 *	);
 *	```
 */

import fs from 'node:fs/promises';

import schema0 from "./Facebook.schema.json" assert { type:"json" };
import schema1 from "./LinkedIn.schema.json" assert { type:"json" };
import schema2 from "./Spotify.schema.json" assert { type:"json" };
import { default as transformer0 } from "./Facebook.transformer.js";
import { default as transformer1 } from "./LinkedIn.transformer.js";
import { default as transformer2 } from "./Spotify.transformer.js";

/** @type {schema: URL|object, name:string, transformer: URL|string}[] */ 
export default [ // transformers
	{schema: schema0, name: "Facebook", transformer: transformer0},
	{schema: schema1, name: "LinkedIn", transformer: transformer1},
	{schema: schema2, name: "Spotify", transformer: transformer2}
];